### PR TITLE
source: add missing #ifndef

### PR DESCRIPTION
**Pull request by SeaHOH**
Fix which due to "warning C4700: uninitialized local variable 'res' used"

### CODE REVIEW

**Comment by albertosottile** [comment]
This completely makes sense, thanks for having spotted this.

**Comment by albertosottile** [comment]
Can you rebase this, so we can check if it passes CI? Thanks

**Comment by SeaHOH** [comment]
There has no conflicts, so just re-run all jobs of the actions?

**Comment by albertosottile** [comment]
I double checked but this is not how it works. Your branch can be rebased automatically but, until it is not, it does not include the fix added in #176, and so the workflow is still failing.

**Comment by SeaHOH** [comment]
Done. A little surprised by its working way.

**Pull request merged**
