### PR TITLE
Support legacy Windows stdio mode

### PR DESCRIPTION
**Pull request by manueljacob**

### CODE REVIEW

**Comment by albertosottile** [comment]
Hi, could you elaborate on what is the purpose of this PR? Also, again, I do not understand why GitHub did not trigger an Action workflow for this...

**Comment by manueljacob** [comment]
Mercurial uses the legacy Windows stdio mode. I can add a bit more text on the commit itself if you want.

**Comment by albertosottile** [comment]
Well, I do not understand entirely what is the use case, which kind of apps are expected, what is the failure that happens in the current code base... `py2exe` is quite old, hence i am surprised that something "legacy" is not supported by it. I would have been less surprised if we needed to add support to a new kind of API, to be honest.

**Comment by mharbison72** [comment]
The "legacy" mode in this case requires an opt-in, because they changed the default behavior of python.

https://peps.python.org/pep-0528/#add-legacy-mode

What I couldn't figure out is why it also seemed to ignore the environment variable, because only the python library should care about that, not py2exe itself.

**Comment by albertosottile** [comment]
So, I finally had the time to have a deep look into this. First of all, the environment variable cannot possibly work because the Python initialization sequence we use in `py2exe` (included in  `start.c`) does not look for it. 

Second, I am not against adding this feature, per se, but I am quite reluctant to modify the `struct` that defines a `py2exe` frozen executable, unless there is an extremely compelling reason.

So, third, I tried to understand better what a possible use case for this would be, but I have to say I did not find any. PEP528 seems to affect only low level manipulations of the console streams, as in https://stackoverflow.com/questions/52373180/python-on-windows-handle-invalid-when-redirecting-stdout-writing-to-file, and these should actually not be done at all, whenever possible. As a matter of fact, PyInstaller does not support this flag https://github.com/pyinstaller/pyinstaller/issues/5227#issuecomment-707880798 , which makes me even more reluctant to merge this.

Finally, I also have to say I do not understand why "Mercurial uses the legacy Windows stdio mode" requires this change in `py2exe`, unless you use the console stream (`ReadConsoleW` and `WriteConsoleW`) to interact with mercurial, and, if that is the case, you should not do that.

Could you provide here an actual use case for having this support in `py2exe`?

**Comment by albertosottile** [comment]
Closing this as stale. Please feel free to re-open it if needed.

**Pull request closed without merging**
